export const statesAndCities = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
  ],
  "Arunachal Pradesh": [
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Kurung Kumey",
    "Kra Daadi",
    "Lower Subansiri",
    "Upper Subansiri",
  ],
  Assam: [
    "Baksa",
    "Barpeta",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Guwahati",
    "Hailakandi",
    "Jorhat",
    "Kamrup",
    "Karbi Anglong",
    "Kokrajhar",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Darbhanga",
    "Gaya",
    "Muzaffarpur",
    "Nalanda",
    "Patna",
    "Purnia",
    "Rohtas",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "South Delhi",
    "West Delhi",
  ],
  Gujarat: [
    "Ahmedabad",
    "Gandhinagar",
    "Rajkot",
    "Surat",
    "Vadodara",
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Kolkata",
    "Murshidabad",
    "Nadia",
    "Purba Medinipur",
    "South 24 Parganas",
    "West Medinipur",
  ],
};

export const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const mockDonors = [
  {
    id: 1,
    name: "Aarav Sharma",
    bloodGroup: "O+",
    age: 27,
    city: "Dehradun",
    state: "Uttarakhand",
    lastDonation: "2025-10-12",
    contact: "+91 98765 43210",
    latitude: 30.3165,
    longitude: 78.0322,
  },
  {
    id: 2,
    name: "Sneha Roy",
    bloodGroup: "A+",
    age: 24,
    city: "Kolkata",
    state: "West Bengal",
    lastDonation: "2025-09-03",
    contact: "+91 91234 56780",
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    id: 3,
    name: "Vikram Singh",
    bloodGroup: "B-",
    age: 31,
    city: "New Delhi",
    state: "Delhi",
    lastDonation: "2025-11-20",
    contact: "+91 99887 77665",
    latitude: 28.6139,
    longitude: 77.209,
  },
  {
    id: 4,
    name: "Priya Das",
    bloodGroup: "AB+",
    age: 29,
    city: "Howrah",
    state: "West Bengal",
    lastDonation: "2025-08-16",
    contact: "+91 90000 12345",
    latitude: 22.5958,
    longitude: 88.2636,
  },
  {
    id: 5,
    name: "Kabir Mehta",
    bloodGroup: "O-",
    age: 35,
    city: "South Delhi",
    state: "Delhi",
    lastDonation: "2025-12-04",
    contact: "+91 97777 44556",
    latitude: 28.5355,
    longitude: 77.241,
  },
  {
    id: 6,
    name: "Nisha Kapoor",
    bloodGroup: "B+",
    age: 26,
    city: "New Delhi",
    state: "Delhi",
    lastDonation: "2026-01-18",
    contact: "+91 98888 22110",
    latitude: 28.6329,
    longitude: 77.2195,
  },
  {
    id: 7,
    name: "Rohan Gupta",
    bloodGroup: "A-",
    age: 33,
    city: "Haridwar",
    state: "Uttarakhand",
    lastDonation: "2025-07-30",
    contact: "+91 90111 22334",
    latitude: 29.9457,
    longitude: 78.1642,
  },
  {
    id: 8,
    name: "Meera Joshi",
    bloodGroup: "AB-",
    age: 28,
    city: "Nainital",
    state: "Uttarakhand",
    lastDonation: "2025-11-02",
    contact: "+91 94567 77889",
    latitude: 29.3919,
    longitude: 79.4542,
  },
  {
    id: 9,
    name: "Sayan Mukherjee",
    bloodGroup: "O+",
    age: 30,
    city: "Kolkata",
    state: "West Bengal",
    lastDonation: "2026-02-12",
    contact: "+91 93300 45678",
    latitude: 22.5411,
    longitude: 88.3378,
  },
  {
    id: 10,
    name: "Ananya Sen",
    bloodGroup: "B+",
    age: 25,
    city: "Howrah",
    state: "West Bengal",
    lastDonation: "2025-10-25",
    contact: "+91 99030 11223",
    latitude: 22.5892,
    longitude: 88.3103,
  },
  {
    id: 11,
    name: "Dev Patel",
    bloodGroup: "A+",
    age: 37,
    city: "Ahmedabad",
    state: "Gujarat",
    lastDonation: "2026-03-01",
    contact: "+91 98240 55221",
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    id: 12,
    name: "Aditi Rao",
    bloodGroup: "O+",
    age: 23,
    city: "Patna",
    state: "Bihar",
    lastDonation: "2025-12-28",
    contact: "+91 91222 33445",
    latitude: 25.5941,
    longitude: 85.1376,
  },
  {
    id: 13,
    name: "Imran Khan",
    bloodGroup: "B-",
    age: 40,
    city: "Muzaffarpur",
    state: "Bihar",
    lastDonation: "2025-09-18",
    contact: "+91 92345 66778",
    latitude: 26.1197,
    longitude: 85.391,
  },
  {
    id: 14,
    name: "Tanya Dutta",
    bloodGroup: "AB+",
    age: 32,
    city: "Guwahati",
    state: "Assam",
    lastDonation: "2026-01-06",
    contact: "+91 93650 77880",
    latitude: 26.1445,
    longitude: 91.7362,
  },
  {
    id: 15,
    name: "Arjun Reddy",
    bloodGroup: "A+",
    age: 29,
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    lastDonation: "2025-08-09",
    contact: "+91 98480 44332",
    latitude: 17.6868,
    longitude: 83.2185,
  },
  {
    id: 16,
    name: "Isha Verma",
    bloodGroup: "O-",
    age: 34,
    city: "Dehradun",
    state: "Uttarakhand",
    lastDonation: "2026-02-21",
    contact: "+91 98970 22119",
    latitude: 30.3256,
    longitude: 78.0437,
  },
];

export const activeEmergencies = [
  {
    id: "emergency-1",
    hospital: "AIIMS Trauma Centre",
    city: "New Delhi",
    state: "Delhi",
    bloodGroup: "O-",
    unitsNeeded: 4,
    unitsMatched: 1,
    priority: "Critical",
    responseWindow: "Under 2 hours",
    contact: "+91 11265 88500",
  },
  {
    id: "emergency-2",
    hospital: "Doon Medical College",
    city: "Dehradun",
    state: "Uttarakhand",
    bloodGroup: "A+",
    unitsNeeded: 3,
    unitsMatched: 2,
    priority: "High",
    responseWindow: "Today",
    contact: "+91 13527 21405",
  },
  {
    id: "emergency-3",
    hospital: "SSKM Hospital",
    city: "Kolkata",
    state: "West Bengal",
    bloodGroup: "B+",
    unitsNeeded: 5,
    unitsMatched: 3,
    priority: "High",
    responseWindow: "Tonight",
    contact: "+91 33220 41100",
  },
  {
    id: "emergency-4",
    hospital: "PMCH Blood Bank",
    city: "Patna",
    state: "Bihar",
    bloodGroup: "AB-",
    unitsNeeded: 2,
    unitsMatched: 0,
    priority: "Critical",
    responseWindow: "Under 4 hours",
    contact: "+91 61223 00345",
  },
];
