export const statesAndCities = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
  ],
  "Arunachal Pradesh": [
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Kurung Kumey",
    "Kra Daadi",
    "Lower Subansiri",
    "Upper Subansiri",
  ],
  Assam: [
    "Baksa",
    "Barpeta",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Jorhat",
    "Kamrup",
    "Karbi Anglong",
    "Kokrajhar",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Darbhanga",
    "Gaya",
    "Muzaffarpur",
    "Nalanda",
    "Patna",
    "Purnia",
    "Rohtas",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "South Delhi",
    "West Delhi",
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Kolkata",
    "Murshidabad",
    "Nadia",
    "Purba Medinipur",
    "South 24 Parganas",
    "West Medinipur",
  ],
};

export const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

export const mockDonors = [
  {
    id: 1,
    name: "Aarav Sharma",
    bloodGroup: "O+",
    age: 27,
    city: "Dehradun",
    state: "Uttarakhand",
    lastDonation: "2025-10-12",
    contact: "+91 98765 43210",
    latitude: 30.3165,
    longitude: 78.0322,
  },
  {
    id: 2,
    name: "Sneha Roy",
    bloodGroup: "A+",
    age: 24,
    city: "Kolkata",
    state: "West Bengal",
    lastDonation: "2025-09-03",
    contact: "+91 91234 56780",
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    id: 3,
    name: "Vikram Singh",
    bloodGroup: "B-",
    age: 31,
    city: "New Delhi",
    state: "Delhi",
    lastDonation: "2025-11-20",
    contact: "+91 99887 77665",
    latitude: 28.6139,
    longitude: 77.209,
  },
  {
    id: 4,
    name: "Priya Das",
    bloodGroup: "AB+",
    age: 29,
    city: "Howrah",
    state: "West Bengal",
    lastDonation: "2025-08-16",
    contact: "+91 90000 12345",
    latitude: 22.5958,
    longitude: 88.2636,
  },
];
